import Classicism.Syntax.Term

/-!
# Conversion

The three relations between terms that the metatheory uses, in the three grades Cian
asked for: the **immediate** conversions, a redex and its contractum; the **one-step**
conversions, an immediate conversion applied somewhere inside a term; and **conversion**
proper, the equivalence relation those generate. There is one of each for β, for η and
for δ, the unfolding of the type-subscripted operations, and `Conv` combines them. This
is Definition A.3 of Dorr's *Elimination*, with the congruence rules made explicit as the
one-step closure and the defined operations' unfolding as a conversion.

There is no α: variables are de Bruijn indices, so terms that differ only by the names of
bound variables are the same term, and α-equivalence is identity. That is the reason for
the choice of representation.
-/

namespace Classicism.Meta

variable {Sig : Signature}

/-! ### Immediate conversions -/

/-- An immediate β-conversion: `(λv. B) A` to `B[A/v]`. -/
inductive Beta : ∀ {Γ : Ctx} {σ : Ty}, Term Sig Γ σ → Term Sig Γ σ → Prop
  | intro {Γ : Ctx} {σ : Ty} {ρ : RTy} (b : Term Sig (σ :: Γ) ρ) (a : Term Sig Γ σ) :
      Beta (.app (.lam b) a) (b.instantiate a)

/-- An immediate η-conversion: `λv. F v` to `F`, for `v` not free in `F`, which in de
Bruijn terms is `λ. (weaken F) 0` to `F`. -/
inductive Eta : ∀ {Γ : Ctx} {σ : Ty}, Term Sig Γ σ → Term Sig Γ σ → Prop
  | intro {Γ : Ctx} {σ : Ty} {ρ : RTy} (f : Term Sig Γ (σ ⇒ ρ)) :
      Eta (.lam (.app f.weaken (.var .zero))) f

/-- An immediate δ-conversion: a type-subscripted operation at a constructor type to its
unfolding, `Term.unfoldR`. -/
def Delta {Γ : Ctx} {σ : Ty} (a b : Term Sig Γ σ) : Prop := a.unfoldR = some b

/-- An immediate β-, η- or δ-conversion. -/
def BetaEta {Γ : Ctx} {σ : Ty} (a b : Term Sig Γ σ) : Prop := Beta a b ∨ Eta a b ∨ Delta a b

/-! ### One-step conversions

`Step R` applies `R` at one position inside a term: at the root, in the function or the
argument of an application, or under an abstraction. This is the congruence closure of
`R`, and it is what makes conversion a congruence with respect to application and
abstraction, the first five clauses of the *Elimination* definition. -/

/-- One step of `R`, somewhere inside a term. -/
inductive Step (R : ∀ {Γ : Ctx} {σ : Ty}, Term Sig Γ σ → Term Sig Γ σ → Prop) :
    ∀ {Γ : Ctx} {σ : Ty}, Term Sig Γ σ → Term Sig Γ σ → Prop
  /-- At the root. -/
  | here {Γ : Ctx} {σ : Ty} {a b : Term Sig Γ σ} : R a b → Step R a b
  /-- In the function of an application. -/
  | appL {Γ : Ctx} {σ : Ty} {ρ : RTy} {f f' : Term Sig Γ (σ ⇒ ρ)} {a : Term Sig Γ σ} :
      Step R f f' → Step R (.app f a) (.app f' a)
  /-- In the argument of an application. -/
  | appR {Γ : Ctx} {σ : Ty} {ρ : RTy} {f : Term Sig Γ (σ ⇒ ρ)} {a a' : Term Sig Γ σ} :
      Step R a a' → Step R (.app f a) (.app f a')
  /-- Under an abstraction. -/
  | lam {Γ : Ctx} {σ : Ty} {ρ : RTy} {b b' : Term Sig (σ :: Γ) ρ} :
      Step R b b' → Step R (.lam b) (.lam b')

/-- A one-step β-conversion. -/
abbrev BetaStep {Γ : Ctx} {σ : Ty} : Term Sig Γ σ → Term Sig Γ σ → Prop := Step Beta
/-- A one-step η-conversion. -/
abbrev EtaStep {Γ : Ctx} {σ : Ty} : Term Sig Γ σ → Term Sig Γ σ → Prop := Step Eta
/-- A one-step β-, η- or δ-conversion. -/
abbrev BetaEtaStep {Γ : Ctx} {σ : Ty} : Term Sig Γ σ → Term Sig Γ σ → Prop := Step BetaEta

/-! ### Conversion proper -/

/-- The equivalence relation generated by `R`: `R` itself, reflexivity, symmetry and
transitivity. -/
inductive EqvGen (R : ∀ {Γ : Ctx} {σ : Ty}, Term Sig Γ σ → Term Sig Γ σ → Prop) :
    ∀ {Γ : Ctx} {σ : Ty}, Term Sig Γ σ → Term Sig Γ σ → Prop
  | rel {Γ : Ctx} {σ : Ty} {a b : Term Sig Γ σ} : R a b → EqvGen R a b
  | refl {Γ : Ctx} {σ : Ty} (a : Term Sig Γ σ) : EqvGen R a a
  | symm {Γ : Ctx} {σ : Ty} {a b : Term Sig Γ σ} : EqvGen R a b → EqvGen R b a
  | trans {Γ : Ctx} {σ : Ty} {a b c : Term Sig Γ σ} : EqvGen R a b → EqvGen R b c → EqvGen R a c

/-- β-equivalence. -/
abbrev BetaEq {Γ : Ctx} {σ : Ty} : Term Sig Γ σ → Term Sig Γ σ → Prop := EqvGen BetaStep
/-- η-equivalence. -/
abbrev EtaEq {Γ : Ctx} {σ : Ty} : Term Sig Γ σ → Term Sig Γ σ → Prop := EqvGen EtaStep
/-- Conversion: βηδ-equivalence, the relation `≡` of the paper. -/
abbrev Conv {Γ : Ctx} {σ : Ty} : Term Sig Γ σ → Term Sig Γ σ → Prop := EqvGen BetaEtaStep

@[inherit_doc] infix:50 " ≡ " => Conv

namespace Conv

variable {Γ : Ctx}

theorem refl {σ : Ty} (a : Term Sig Γ σ) : a ≡ a := EqvGen.refl a
theorem symm {σ : Ty} {a b : Term Sig Γ σ} (h : a ≡ b) : b ≡ a := EqvGen.symm h
theorem trans {σ : Ty} {a b c : Term Sig Γ σ} (h₁ : a ≡ b) (h₂ : b ≡ c) : a ≡ c :=
  EqvGen.trans h₁ h₂

/-- The β rule. -/
theorem beta {σ : Ty} {ρ : RTy} (b : Term Sig (σ :: Γ) ρ) (a : Term Sig Γ σ) :
    Term.app (.lam b) a ≡ b.instantiate a :=
  EqvGen.rel (Step.here (Or.inl (Beta.intro b a)))

/-- The η rule. -/
theorem eta {σ : Ty} {ρ : RTy} (f : Term Sig Γ (σ ⇒ ρ)) :
    Term.lam (.app f.weaken (.var .zero)) ≡ f :=
  EqvGen.rel (Step.here (Or.inr (Or.inl (Eta.intro f))))

/-- The δ rule: an operation unfolds. -/
theorem delta {σ : Ty} {a b : Term Sig Γ σ} (h : a.unfoldR = some b) : a ≡ b :=
  EqvGen.rel (Step.here (Or.inr (Or.inr h)))

/-- Conversion is a congruence: the one-step closure lifts through the equivalence
closure, so `EqvGen (Step R)` is closed under each of the term formers. -/
theorem app_congr {σ : Ty} {ρ : RTy} {f f' : Term Sig Γ (σ ⇒ ρ)} {a a' : Term Sig Γ σ}
    (hf : f ≡ f') (ha : a ≡ a') : Term.app f a ≡ Term.app f' a' :=
  EqvGen.trans (appL hf) (appR ha)
where
  appL {f f' : Term Sig Γ (σ ⇒ ρ)} {a : Term Sig Γ σ} (h : f ≡ f') :
      Term.app f a ≡ Term.app f' a := by
    induction h with
    | rel h => exact EqvGen.rel (Step.appL h)
    | refl _ => exact EqvGen.refl _
    | symm _ ih => exact EqvGen.symm ih
    | trans _ _ ih₁ ih₂ => exact EqvGen.trans ih₁ ih₂
  appR {f : Term Sig Γ (σ ⇒ ρ)} {a a' : Term Sig Γ σ} (h : a ≡ a') :
      Term.app f a ≡ Term.app f a' := by
    induction h with
    | rel h => exact EqvGen.rel (Step.appR h)
    | refl _ => exact EqvGen.refl _
    | symm _ ih => exact EqvGen.symm ih
    | trans _ _ ih₁ ih₂ => exact EqvGen.trans ih₁ ih₂

theorem lam_congr {σ : Ty} {ρ : RTy} {b b' : Term Sig (σ :: Γ) ρ} (h : b ≡ b') :
    Term.lam b ≡ Term.lam b' := by
  induction h with
  | rel h => exact EqvGen.rel (Step.lam h)
  | refl _ => exact EqvGen.refl _
  | symm _ ih => exact EqvGen.symm ih
  | trans _ _ ih₁ ih₂ => exact EqvGen.trans ih₁ ih₂

end Conv

/-! ### Conversion is stable under renaming -/

theorem Term.weaken_rename {Γ Δ : Ctx} {σ τ : Ty} (r : Ren Γ Δ) (a : Term Sig Γ σ) :
    (a.rename r).weaken (τ := τ) = a.weaken.rename (Ren.lift r) := by
  simp only [Term.weaken, Term.rename_rename]; rfl

theorem Term.instantiate_rename {Γ Δ : Ctx} {σ τ : Ty} (r : Ren Γ Δ) (b : Term Sig (σ :: Γ) τ)
    (a : Term Sig Γ σ) :
    (b.instantiate a).rename r = (b.rename (Ren.lift r)).instantiate (a.rename r) := by
  simp only [Term.instantiate, Term.rename_subst, Term.subst_rename]
  congr 1
  funext υ v
  cases v with
  | zero => rfl
  | succ v => rfl

theorem Beta.rename {Γ Δ : Ctx} {σ : Ty} (r : Ren Γ Δ) {a b : Term Sig Γ σ} (h : Beta a b) :
    Beta (a.rename r) (b.rename r) := by
  cases h with
  | intro b a =>
    rw [Term.instantiate_rename]
    exact Beta.intro _ _

theorem Eta.rename {Γ Δ : Ctx} {σ : Ty} (r : Ren Γ Δ) {a b : Term Sig Γ σ} (h : Eta a b) :
    Eta (a.rename r) (b.rename r) := by
  cases h with
  | intro f =>
    show Eta (.lam (.app (f.weaken.rename (Ren.lift r)) (.var .zero))) (f.rename r)
    rw [← Term.weaken_rename]
    exact Eta.intro _

/-- The unfoldings are closed terms: renaming passes through them. -/
theorem Term.unfoldR_rename : ∀ {Γ Δ : Ctx} (r : Ren Γ Δ) {σ : Ty} (a : Term Sig Γ σ),
    (a.rename r).unfoldR = a.unfoldR.map (Term.rename r)
  | _, _, _, _, .var _ | _, _, _, _, .const _ | _, _, _, _, .and | _, _, _, _, .or
  | _, _, _, _, .not | _, _, _, _, .all _ | _, _, _, _, .ex _ | _, _, _, _, .eq _
  | _, _, _, _, .app _ _ | _, _, _, _, .lam _ => rfl
  | _, _, _, _, .constR ρ | _, _, _, _, .negR ρ | _, _, _, _, .andR ρ | _, _, _, _, .orR ρ
  | _, _, _, _, .coextR ρ | _, _, _, _, .boxR ρ | _, _, _, _, .boxImpR ρ => by cases ρ <;> rfl

theorem Delta.rename {Γ Δ : Ctx} {σ : Ty} (r : Ren Γ Δ) {a b : Term Sig Γ σ} (h : Delta a b) :
    Delta (a.rename r) (b.rename r) := by
  unfold Delta at *
  rw [Term.unfoldR_rename, h]; rfl

theorem BetaEta.rename {Γ Δ : Ctx} {σ : Ty} (r : Ren Γ Δ) {a b : Term Sig Γ σ} (h : BetaEta a b) :
    BetaEta (a.rename r) (b.rename r) :=
  h.elim (fun h => Or.inl (Beta.rename r h))
    (fun h => h.elim (fun h => Or.inr (Or.inl (Eta.rename r h))) (fun h => Or.inr (Or.inr (Delta.rename r h))))

theorem Step.rename {R : ∀ {Γ : Ctx} {σ : Ty}, Term Sig Γ σ → Term Sig Γ σ → Prop}
    (hR : ∀ {Γ Δ : Ctx} {σ : Ty} (r : Ren Γ Δ) {a b : Term Sig Γ σ}, R a b → R (a.rename r) (b.rename r)) :
    ∀ {Γ Δ : Ctx} {σ : Ty} (r : Ren Γ Δ) {a b : Term Sig Γ σ}, Step R a b →
      Step R (a.rename r) (b.rename r)
  | _, _, _, r, _, _, .here h => .here (hR r h)
  | _, _, _, r, _, _, .appL h => .appL (Step.rename hR r h)
  | _, _, _, r, _, _, .appR h => .appR (Step.rename hR r h)
  | _, _, _, r, _, _, .lam h => .lam (Step.rename hR (Ren.lift r) h)

theorem Conv.rename {Γ Δ : Ctx} {σ : Ty} (r : Ren Γ Δ) {a b : Term Sig Γ σ} (h : a ≡ b) :
    a.rename r ≡ b.rename r := by
  induction h with
  | rel h => exact EqvGen.rel (Step.rename BetaEta.rename r h)
  | refl _ => exact EqvGen.refl _
  | symm _ ih => exact EqvGen.symm ih
  | trans _ _ ih₁ ih₂ => exact EqvGen.trans ih₁ ih₂

end Classicism.Meta
