import Classicism.Syntax.Conversion

/-!
# Derivability

`Derivable Ax Δ p` says that the formula `p` is derivable from the hypotheses `Δ` in the
system `H` closed under the rule Subst, extended by the sentences in `Ax` as axioms. It is
an inductive relation, so it is *by definition* the smallest relation closed under the
rules: the paper's notion of a theory generated by axioms, with Classicism itself the case
of the logical axioms alone. A proof of `Derivable Ax Δ p` is a derivation tree, built
from the constructors below, and that is all a derivation ever needs to be; see the README
on why derivations are not a separate datatype.

The rules are those of `H` in **natural-deduction form**, which is the form Lean's proof
terms have and the form the translator from shallow proofs emits. Hypotheses are a list
`Δ` beside the variable context `Γ`; a variable rule with an eigenvariable, `allI` and
`exE`, weakens every hypothesis into the extended context, which is the side condition
"`v` not free in the hypotheses" made structural.

* PC is the introduction and elimination rules for `∧`, `∨` and `¬`, with excluded middle,
  from which every tautology is derivable.
* UI and EG are `allE` and `exI`, with an arbitrary term `F : σ → t` in the quantifier's
  argument position, as the paper states them; Gen and Inst are `allI` and `exE`.
* Ref and LL are `refl` and `ll`.
* β, η and δ are the single rule `conv`: a derivation transfers along conversion.
* The axioms of the theory are cited by `ax`, at any context, since they are sentences.
* **Subst**, the rule of *Elimination* that makes `H` into Classicism: from `P ⊢ Q` and
  `Q ⊢ P`, each *on its own*, and `Δ ⊢ R[P]`, infer `Δ ⊢ R[Q]`, for `R` any formula with
  one hole for a formula, the hole possibly under binders (`Hole`, below). It gives no
  logical constant a special role; the rule of Equivalence is its instance at the hole
  `P = ⬚`, and ξ its instance with the hole under an abstraction.

"On its own" is the substance of the rule. The premises `P ⊢ Q` and `Q ⊢ P` are
derivations from the hypothesis alone, in the *logical* part of the theory: no side
hypotheses, and none of the theory's proper axioms. Were the axioms admitted there, a
theory `C + BF` would derive `BF ↔ ⊤` from its axiom, hence `BF = ⊤`, hence `□BF`, and
the map's distinction between `BF` and `□BF` would collapse. So the axiom set is an
*index* of the inductive, and Subst's premises are at `Ax.logical`, which keeps Existence
at `e` (all that `H` assumes beyond its rules) and nothing else.

Nothing is a special rule. Classicism is `Derivable Logical`; the eleven identities of
`Classicism/Meta/Axioms.lean`, its axiomatization by Appendix A, are theorems of it.
-/

namespace Classicism.Meta

variable {Sig : Signature}

/-- The renaming from the empty context into any context. -/
def Ren.ofEmpty {Γ : Ctx} : Ren [] Γ := fun _ v => nomatch v

/-- A closed term, placed in a context. -/
abbrev Term.close {Γ : Ctx} {σ : Ty} (a : Term Sig [] σ) : Term Sig Γ σ := a.rename Ren.ofEmpty

/-- A list of hypotheses, weakened into a context with one more variable. -/
abbrev Hyps.weaken {Γ : Ctx} {σ : Ty} (Δ : List (Formula Sig Γ)) : List (Formula Sig (σ :: Γ)) :=
  Δ.map Term.weaken

/-- A set of axioms: a property of sentences. -/
abbrev AxiomSet (Sig : Signature) : Type := Sentence Sig → Prop

/-! ### The logical axioms -/

/-- Existence at `e`: `∃x:e. x = x`. `H` assumes every type inhabited; the rules alone
prove this at every relational type (`λx. ⊤` is a closed term there) but not at `e`,
where the empty context has no term. So it is the one axiom of `H` beyond its rules, and
the line between `H⁻` and `H` (Classicism, nn. 12–13). -/
def existence_e : Sentence Sig := Term.exists' (σ := Ty.e) (Term.eq' Term.v0 Term.v0)

/-- The logical axioms: Existence at `e`. -/
def Logical : AxiomSet Sig := fun a => a = existence_e

/-- The logical part of an axiom set: its logical axioms, and nothing proper to the theory. -/
def AxiomSet.logical (Ax : AxiomSet Sig) : AxiomSet Sig := fun a => Ax a ∧ Logical a

/-! ### One-hole contexts

The rule Subst substitutes for a propositional variable anywhere in a formula, under
binders included, and the two premises may then mention the bound variables. With
intrinsically typed terms that is a term with a hole: `Hole Sig Γ σ Γ' τ` is a term of
type `σ` in context `Γ` with one hole for a term of type `τ` whose context is `Γ'`, the
context `Γ` extended by the binders the hole lies under. -/

/-- A term with one hole. -/
inductive Hole (Sig : Signature) : Ctx → Ty → Ctx → Ty → Type
  /-- The hole itself. -/
  | hole {Γ : Ctx} {τ : Ty} : Hole Sig Γ τ Γ τ
  /-- The hole in the function position of an application. -/
  | appL {Γ Γ' : Ctx} {σ : Ty} {ρ : RTy} {τ : Ty} :
      Hole Sig Γ (σ ⇒ ρ) Γ' τ → Term Sig Γ σ → Hole Sig Γ ρ Γ' τ
  /-- The hole in the argument position of an application. -/
  | appR {Γ Γ' : Ctx} {σ : Ty} {ρ : RTy} {τ : Ty} :
      Term Sig Γ (σ ⇒ ρ) → Hole Sig Γ σ Γ' τ → Hole Sig Γ ρ Γ' τ
  /-- The hole under an abstraction. -/
  | lam {Γ Γ' : Ctx} {σ : Ty} {ρ : RTy} {τ : Ty} :
      Hole Sig (σ :: Γ) ρ Γ' τ → Hole Sig Γ (σ ⇒ ρ) Γ' τ

namespace Hole

/-- Fill the hole. -/
def plug : ∀ {Γ Γ' : Ctx} {σ τ : Ty}, Hole Sig Γ σ Γ' τ → Term Sig Γ' τ → Term Sig Γ σ
  | _, _, _, _, hole, a => a
  | _, _, _, _, appL C b, a => .app (plug C a) b
  | _, _, _, _, appR f C, a => .app f (plug C a)
  | _, _, _, _, lam C, a => .lam (plug C a)

/-- A hole inside a hole. -/
def comp : ∀ {Γ Γ' Γ'' : Ctx} {σ τ υ : Ty},
    Hole Sig Γ σ Γ' τ → Hole Sig Γ' τ Γ'' υ → Hole Sig Γ σ Γ'' υ
  | _, _, _, _, _, _, hole, D => D
  | _, _, _, _, _, _, appL C b, D => appL (comp C D) b
  | _, _, _, _, _, _, appR f C, D => appR f (comp C D)
  | _, _, _, _, _, _, lam C, D => lam (comp C D)

theorem plug_comp : ∀ {Γ Γ' Γ'' : Ctx} {σ τ υ : Ty} (C : Hole Sig Γ σ Γ' τ)
    (D : Hole Sig Γ' τ Γ'' υ) (a : Term Sig Γ'' υ), (C.comp D).plug a = C.plug (D.plug a)
  | _, _, _, _, _, _, hole, _, _ => rfl
  | _, _, _, _, _, _, appL C b, D, a => by simp only [comp, plug, plug_comp C D a]
  | _, _, _, _, _, _, appR f C, D, a => by simp only [comp, plug, plug_comp C D a]
  | _, _, _, _, _, _, lam C, D, a => by simp only [comp, plug, plug_comp C D a]

/-- Filling a hole is a congruence for conversion. -/
theorem plug_conv : ∀ {Γ Γ' : Ctx} {σ τ : Ty} (C : Hole Sig Γ σ Γ' τ) {a b : Term Sig Γ' τ},
    a ≡ b → C.plug a ≡ C.plug b
  | _, _, _, _, hole, _, _, h => h
  | _, _, _, _, appL C _, _, _, h => Conv.app_congr (plug_conv C h) (Conv.refl _)
  | _, _, _, _, appR _ C, _, _, h => Conv.app_congr (Conv.refl _) (plug_conv C h)
  | _, _, _, _, lam C, _, _, h => Conv.lam_congr (plug_conv C h)

/-- A renamed hole: the hole, the context its hole now has, and the renaming into it. -/
structure Renamed (Sig : Signature) (Δ : Ctx) (σ : Ty) (Γ' : Ctx) (τ : Ty) where
  ctx : Ctx
  hole : Hole Sig Δ σ ctx τ
  ren : Ren Γ' ctx

/-- Rename the variables of a hole; under an abstraction the renaming is lifted, so the
hole's own context is renamed by the lifted renaming, which is returned. -/
def rename : ∀ {Γ Δ Γ' : Ctx} {σ τ : Ty}, Ren Γ Δ → Hole Sig Γ σ Γ' τ → Renamed Sig Δ σ Γ' τ
  | _, Δ, _, _, _, r, hole => ⟨Δ, hole, r⟩
  | _, _, _, _, _, r, appL C b => let R := rename r C; ⟨R.ctx, appL R.hole (b.rename r), R.ren⟩
  | _, _, _, _, _, r, appR f C => let R := rename r C; ⟨R.ctx, appR (f.rename r) R.hole, R.ren⟩
  | _, _, _, _, _, r, lam C => let R := rename (Ren.lift r) C; ⟨R.ctx, lam R.hole, R.ren⟩

theorem plug_rename : ∀ {Γ Δ Γ' : Ctx} {σ τ : Ty} (r : Ren Γ Δ) (C : Hole Sig Γ σ Γ' τ)
    (a : Term Sig Γ' τ), (C.plug a).rename r = (C.rename r).hole.plug (a.rename (C.rename r).ren)
  | _, _, _, _, _, _, hole, _ => rfl
  | _, _, _, _, _, r, appL C b, a => by simp only [plug, rename, Term.rename_app, plug_rename r C a]
  | _, _, _, _, _, r, appR f C, a => by simp only [plug, rename, Term.rename_app, plug_rename r C a]
  | _, _, _, _, _, r, lam C, a => by simp only [plug, rename, Term.rename_lam, plug_rename (Ren.lift r) C a]

end Hole

/-- Derivability in `H` closed under Subst, plus the axioms `Ax`, from hypotheses `Δ`, in
context `Γ`. The axiom set is an index, since Subst's premises are at its logical part. -/
inductive Derivable : AxiomSet Sig → ∀ {Γ : Ctx}, List (Formula Sig Γ) → Formula Sig Γ → Prop
  /-- A hypothesis. -/
  | hyp {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p : Formula Sig Γ} :
      p ∈ Δ → Derivable Ax Δ p
  /-- An axiom of the theory, at any context. -/
  | ax {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {a : Sentence Sig} :
      Ax a → Derivable Ax Δ a.close
  /-- `∧`-introduction. -/
  | andI {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p q : Formula Sig Γ} :
      Derivable Ax Δ p → Derivable Ax Δ q → Derivable Ax Δ (Term.conj p q)
  /-- `∧`-elimination, left. -/
  | andE₁ {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p q : Formula Sig Γ} :
      Derivable Ax Δ (Term.conj p q) → Derivable Ax Δ p
  /-- `∧`-elimination, right. -/
  | andE₂ {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p q : Formula Sig Γ} :
      Derivable Ax Δ (Term.conj p q) → Derivable Ax Δ q
  /-- `∨`-introduction, left. -/
  | orI₁ {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p q : Formula Sig Γ} :
      Derivable Ax Δ p → Derivable Ax Δ (Term.disj p q)
  /-- `∨`-introduction, right. -/
  | orI₂ {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p q : Formula Sig Γ} :
      Derivable Ax Δ q → Derivable Ax Δ (Term.disj p q)
  /-- `∨`-elimination: by cases. -/
  | orE {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p q r : Formula Sig Γ} :
      Derivable Ax Δ (Term.disj p q) → Derivable Ax (p :: Δ) r → Derivable Ax (q :: Δ) r →
      Derivable Ax Δ r
  /-- `¬`-introduction: what yields a contradiction is false. -/
  | notI {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p q : Formula Sig Γ} :
      Derivable Ax (p :: Δ) q → Derivable Ax (p :: Δ) (Term.neg q) → Derivable Ax Δ (Term.neg p)
  /-- `¬`-elimination: from a contradiction, anything. -/
  | notE {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p q : Formula Sig Γ} :
      Derivable Ax Δ p → Derivable Ax Δ (Term.neg p) → Derivable Ax Δ q
  /-- Excluded middle, which makes the propositional fragment classical. -/
  | em {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} (p : Formula Sig Γ) :
      Derivable Ax Δ (Term.disj p (Term.neg p))
  /-- `UI`: `∀σ F → F A`, for any predicate term `F`. -/
  | allE {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {σ : Ty} {F : Term Sig Γ (σ ⇒ RTy.t)} :
      Derivable Ax Δ (.app (.all σ) F) → (a : Term Sig Γ σ) → Derivable Ax Δ (.app F a)
  /-- `Gen`: from `b`, derived with a fresh variable and hypotheses not mentioning it,
  `∀v. b`. -/
  | allI {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {σ : Ty} {b : Formula Sig (σ :: Γ)} :
      Derivable Ax (Hyps.weaken Δ) b → Derivable Ax Δ (Term.forall' b)
  /-- `EG`: `F A → ∃σ F`. -/
  | exI {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {σ : Ty} {F : Term Sig Γ (σ ⇒ RTy.t)}
      (a : Term Sig Γ σ) : Derivable Ax Δ (.app F a) → Derivable Ax Δ (.app (.ex σ) F)
  /-- `Inst`: from `∃σ F`, and `r` derived from `F v` for a fresh `v`, `r`. -/
  | exE {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {σ : Ty} {F : Term Sig Γ (σ ⇒ RTy.t)}
      {r : Formula Sig Γ} :
      Derivable Ax Δ (.app (.ex σ) F) →
      Derivable Ax (Term.app F.weaken (.var .zero) :: Hyps.weaken Δ) r.weaken →
      Derivable Ax Δ r
  /-- `Ref`: `A = A`. -/
  | refl {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {σ : Ty} (a : Term Sig Γ σ) :
      Derivable Ax Δ (Term.eq' a a)
  /-- `LL`: from `A = B` and `F A`, `F B`. -/
  | ll {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {σ : Ty} {a b : Term Sig Γ σ}
      (F : Term Sig Γ (σ ⇒ RTy.t)) :
      Derivable Ax Δ (Term.eq' a b) → Derivable Ax Δ (.app F a) → Derivable Ax Δ (.app F b)
  /-- `β`, `η` and `δ`: derivability transfers along conversion. -/
  | conv {Ax : AxiomSet Sig} {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p q : Formula Sig Γ} :
      Derivable Ax Δ p → p ≡ q → Derivable Ax Δ q
  /-- **Subst**: from `P ⊢ Q` and `Q ⊢ P`, each on its own in the logical part of the
  theory, and `Δ ⊢ R[P]`, infer `Δ ⊢ R[Q]`, for `R` a formula with one hole for a
  formula, under binders or not. -/
  | subst {Ax : AxiomSet Sig} {Γ Γ' : Ctx} {Δ : List (Formula Sig Γ)} {P Q : Formula Sig Γ'}
      (C : Hole Sig Γ Ty.t Γ' Ty.t) :
      Derivable Ax.logical [P] Q → Derivable Ax.logical [Q] P →
      Derivable Ax Δ (C.plug P) → Derivable Ax Δ (C.plug Q)

/-- `p` is a theorem of the theory `Ax`: derivable from no hypotheses, in the empty
context. -/
abbrev Theorem (Ax : AxiomSet Sig) (p : Sentence Sig) : Prop := Derivable Ax [] p

namespace Derivable

/-! ### Structural facts -/

theorem _root_.Classicism.Meta.AxiomSet.logical_mono {Ax Ax' : AxiomSet Sig}
    (hA : ∀ a, Ax a → Ax' a) : ∀ a, Ax.logical a → Ax'.logical a :=
  fun a ⟨h, hl⟩ => ⟨hA a h, hl⟩

theorem _root_.List.map_subset_of_subset {α β : Type} (f : α → β) {l l' : List α}
    (h : l ⊆ l') : l.map f ⊆ l'.map f := by
  intro x hx
  rw [List.mem_map] at hx ⊢
  obtain ⟨a, ha, rfl⟩ := hx
  exact ⟨a, h ha, rfl⟩

/-- Weakening: more hypotheses derive no less. Admissible, by induction on the derivation;
the eigenvariable rules need that weakening commutes with the context extension. -/
theorem weaken {Ax : AxiomSet Sig} : ∀ {Γ : Ctx} {Δ Δ' : List (Formula Sig Γ)} {p : Formula Sig Γ},
    Derivable Ax Δ p → Δ ⊆ Δ' → Derivable Ax Δ' p
  | _, _, _, _, hyp h, hs => hyp (hs h)
  | _, _, _, _, ax h, _ => ax h
  | _, _, _, _, andI h₁ h₂, hs => andI (weaken h₁ hs) (weaken h₂ hs)
  | _, _, _, _, andE₁ h, hs => andE₁ (weaken h hs)
  | _, _, _, _, andE₂ h, hs => andE₂ (weaken h hs)
  | _, _, _, _, orI₁ h, hs => orI₁ (weaken h hs)
  | _, _, _, _, orI₂ h, hs => orI₂ (weaken h hs)
  | _, _, _, _, orE h h₁ h₂, hs =>
    orE (weaken h hs) (weaken h₁ (List.cons_subset_cons _ hs)) (weaken h₂ (List.cons_subset_cons _ hs))
  | _, _, _, _, notI h₁ h₂, hs =>
    notI (weaken h₁ (List.cons_subset_cons _ hs)) (weaken h₂ (List.cons_subset_cons _ hs))
  | _, _, _, _, notE h₁ h₂, hs => notE (weaken h₁ hs) (weaken h₂ hs)
  | _, _, _, _, em p, _ => em p
  | _, _, _, _, allE h a, hs => allE (weaken h hs) a
  | _, _, _, _, allI h, hs => allI (weaken h (List.map_subset_of_subset _ hs))
  | _, _, _, _, exI a h, hs => exI a (weaken h hs)
  | _, _, _, _, exE h h', hs =>
    exE (weaken h hs) (weaken h' (List.cons_subset_cons _ (List.map_subset_of_subset _ hs)))
  | _, _, _, _, refl a, _ => refl a
  | _, _, _, _, ll F h₁ h₂, hs => ll F (weaken h₁ hs) (weaken h₂ hs)
  | _, _, _, _, conv h c, hs => conv (weaken h hs) c
  | _, _, _, _, subst C h₁ h₂ h₃, hs => subst C h₁ h₂ (weaken h₃ hs)

/-- Hypotheses, renamed. -/
abbrev _root_.Classicism.Meta.Hyps.rename {Γ Δ : Ctx} (r : Ren Γ Δ) (Δ' : List (Formula Sig Γ)) :
    List (Formula Sig Δ) := Δ'.map (Term.rename r)

theorem _root_.Classicism.Meta.Hyps.weaken_rename {Γ Δ : Ctx} {σ : Ty} (r : Ren Γ Δ)
    (Δ' : List (Formula Sig Γ)) :
    Hyps.weaken (σ := σ) (Hyps.rename r Δ') = Hyps.rename (Ren.lift r) (Hyps.weaken Δ') := by
  simp only [Hyps.weaken, Hyps.rename, List.map_map]
  congr 1
  funext a
  exact Term.weaken_rename r a

/-- Renaming the variables: a derivation in one context gives a derivation in any context
it maps into. Admissible by induction; the eigenvariable rules lift the renaming. -/
theorem rename : ∀ {Ax : AxiomSet Sig} {Γ Δ : Ctx} (r : Ren Γ Δ) {Δ' : List (Formula Sig Γ)}
    {p : Formula Sig Γ}, Derivable Ax Δ' p → Derivable Ax (Hyps.rename r Δ') (p.rename r)
  | _, _, _, r, _, _, hyp h => hyp (List.mem_map.2 ⟨_, h, rfl⟩)
  | _, _, _, r, _, _, ax (a := a) h => by
    have : (Term.close a).rename r = Term.close a := by
      simp only [Term.close, Term.rename_rename]
      congr 1; funext σ v; exact nomatch v
    rw [this]; exact ax h
  | _, _, _, r, _, _, andI h₁ h₂ => andI (rename r h₁) (rename r h₂)
  | _, _, _, r, _, _, andE₁ h => andE₁ (rename r h)
  | _, _, _, r, _, _, andE₂ h => andE₂ (rename r h)
  | _, _, _, r, _, _, orI₁ h => orI₁ (rename r h)
  | _, _, _, r, _, _, orI₂ h => orI₂ (rename r h)
  | _, _, _, r, _, _, orE h h₁ h₂ => orE (rename r h) (rename r h₁) (rename r h₂)
  | _, _, _, r, _, _, notI h₁ h₂ => notI (rename r h₁) (rename r h₂)
  | _, _, _, r, _, _, notE h₁ h₂ => notE (rename r h₁) (rename r h₂)
  | _, _, _, r, _, _, em p => em _
  | _, _, _, r, _, _, allE h a => allE (rename r h) (a.rename r)
  | _, _, _, r, _, _, allI h => by
    have := rename (Ren.lift r) h
    rw [← Hyps.weaken_rename] at this
    exact allI this
  | _, _, _, r, _, _, exI a h => exI (a.rename r) (rename r h)
  | _, _, _, r, Δ', _, exE (σ := σ) (F := F) (r := q) h h' => by
    have this := rename (Ren.lift r) h'
    have e₁ : Hyps.rename (Ren.lift r) (Term.app F.weaken (.var .zero) :: Hyps.weaken Δ')
        = Term.app (F.rename r).weaken (.var .zero) :: Hyps.weaken (Hyps.rename r Δ') := by
      simp only [Hyps.rename, List.map_cons, Hyps.weaken_rename, Term.weaken_rename]
      rfl
    have e₂ : q.weaken.rename (Ren.lift r) = (q.rename r).weaken (τ := σ) :=
      (Term.weaken_rename (τ := σ) r q).symm
    rw [e₁, e₂] at this
    exact exE (rename r h) this
  | _, _, _, r, _, _, refl a => refl _
  | _, _, _, r, _, _, ll F h₁ h₂ => ll (F.rename r) (rename r h₁) (rename r h₂)
  | _, _, _, r, _, _, subst (P := P) (Q := Q) C h₁ h₂ h₃ => by
    have h₁' := rename (C.rename r).ren h₁
    have h₂' := rename (C.rename r).ren h₂
    have h₃' := rename r h₃
    rw [Hole.plug_rename] at h₃' ⊢
    exact subst (C.rename r).hole h₁' h₂' h₃'
  | _, _, _, r, _, _, conv h c => conv (rename r h) (Conv.rename r c)

variable {Ax : AxiomSet Sig}

/-- A theorem holds in every context, from any hypotheses. -/
theorem ofTheorem {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p : Sentence Sig} (h : Theorem Ax p) :
    Derivable Ax Δ p.close :=
  weaken (rename Ren.ofEmpty h) (fun _ h => nomatch h)

/-- A hypothesis just added. -/
theorem hyp₀ {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p : Formula Sig Γ} :
    Derivable Ax (p :: Δ) p := hyp (List.mem_cons_self ..)

/-- Add one hypothesis. -/
theorem weaken₁ {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p q : Formula Sig Γ}
    (h : Derivable Ax Δ p) : Derivable Ax (q :: Δ) p :=
  weaken h (List.subset_cons_self _ _)

/-- More axioms derive no less. -/
theorem mono : ∀ {Ax Ax' : AxiomSet Sig}, (∀ a, Ax a → Ax' a) →
    ∀ {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p : Formula Sig Γ},
      Derivable Ax Δ p → Derivable Ax' Δ p
  | _, _, _, _, _, _, hyp h => hyp h
  | _, _, hA, _, _, _, ax h => ax (hA _ h)
  | _, _, hA, _, _, _, andI h₁ h₂ => andI (mono hA h₁) (mono hA h₂)
  | _, _, hA, _, _, _, andE₁ h => andE₁ (mono hA h)
  | _, _, hA, _, _, _, andE₂ h => andE₂ (mono hA h)
  | _, _, hA, _, _, _, orI₁ h => orI₁ (mono hA h)
  | _, _, hA, _, _, _, orI₂ h => orI₂ (mono hA h)
  | _, _, hA, _, _, _, orE h h₁ h₂ => orE (mono hA h) (mono hA h₁) (mono hA h₂)
  | _, _, hA, _, _, _, notI h₁ h₂ => notI (mono hA h₁) (mono hA h₂)
  | _, _, hA, _, _, _, notE h₁ h₂ => notE (mono hA h₁) (mono hA h₂)
  | _, _, hA, _, _, _, em p => em p
  | _, _, hA, _, _, _, allE h a => allE (mono hA h) a
  | _, _, hA, _, _, _, allI h => allI (mono hA h)
  | _, _, hA, _, _, _, exI a h => exI a (mono hA h)
  | _, _, hA, _, _, _, exE h h' => exE (mono hA h) (mono hA h')
  | _, _, hA, _, _, _, refl a => refl a
  | _, _, hA, _, _, _, ll F h₁ h₂ => ll F (mono hA h₁) (mono hA h₂)
  | _, _, hA, _, _, _, subst C h₁ h₂ h₃ =>
    subst C (mono (AxiomSet.logical_mono hA) h₁) (mono (AxiomSet.logical_mono hA) h₂) (mono hA h₃)
  | _, _, hA, _, _, _, conv h c => conv (mono hA h) c

/-! ### The defined connectives

`→` is `¬p ∨ q` and `↔` a conjunction of two of those, so their rules are derived. -/

variable {Γ : Ctx} {Δ : List (Formula Sig Γ)} {p q : Formula Sig Γ}

/-- `→`-introduction, by excluded middle on the antecedent. -/
theorem impI (h : Derivable Ax (p :: Δ) q) : Derivable Ax Δ (Term.imp p q) :=
  orE (em p) (orI₂ h) (orI₁ hyp₀)

/-- `→`-elimination, modus ponens. -/
theorem impE (h : Derivable Ax Δ (Term.imp p q)) (hp : Derivable Ax Δ p) : Derivable Ax Δ q :=
  orE h (notE (weaken₁ hp) hyp₀) hyp₀

theorem iffI (h₁ : Derivable Ax (p :: Δ) q) (h₂ : Derivable Ax (q :: Δ) p) :
    Derivable Ax Δ (Term.iff p q) :=
  andI (impI h₁) (impI h₂)

theorem iffE₁ (h : Derivable Ax Δ (Term.iff p q)) (hp : Derivable Ax Δ p) : Derivable Ax Δ q :=
  impE (andE₁ h) hp

theorem iffE₂ (h : Derivable Ax Δ (Term.iff p q)) (hq : Derivable Ax Δ q) : Derivable Ax Δ p :=
  impE (andE₂ h) hq

/-- `⊤` is a theorem of every theory: it is an instance of excluded middle. -/
theorem top : Derivable Ax Δ Term.top := em _

/-- From `⊥`, anything. -/
theorem botE (h : Derivable Ax Δ Term.bot) : Derivable Ax Δ p := notE (andE₁ h) (andE₂ h)

/-- Symmetry of identity, from `Ref` and `LL` at the predicate `λz. z = a`. -/
theorem eqSymm {σ : Ty} {a b : Term Sig Γ σ} (h : Derivable Ax Δ (Term.eq' a b)) :
    Derivable Ax Δ (Term.eq' b a) :=
  have h₁ : Derivable Ax Δ (.app (.lam (Term.eq' (.var .zero) a.weaken)) b) :=
    ll (.lam (Term.eq' (.var .zero) a.weaken)) h
      (conv (refl a) (Conv.symm (by
        have := Conv.beta (Sig := Sig) (Γ := Γ) (Term.eq' (.var .zero) a.weaken) a
        simpa [Term.instantiate, Term.subst_rename, Term.subst_id] using this)))
  conv h₁ (by
    have := Conv.beta (Sig := Sig) (Γ := Γ) (Term.eq' (.var .zero) a.weaken) b
    simpa [Term.instantiate, Term.subst_rename, Term.subst_id] using this)

/-! ### Leibniz's Law in the forms the translator meets

The strict layer's proofs are equational: Lean's `congrArg`, `Eq.trans`, `Eq.symm`,
`Eq.mpr` and `congrFun` are each `LL` at a particular predicate, and these are their
derivations. Each ends in a `conv` that β-reduces the predicate's application. -/

/-- The conversion `(λz. B) a ≡ B[a]`, for use in the rules below. -/
theorem _root_.Classicism.Meta.Conv.beta' {σ : Ty} {ρ : RTy} (b : Term Sig (σ :: Γ) ρ)
    (a : Term Sig Γ σ) : Term.app (.lam b) a ≡ b.instantiate a := Conv.beta b a

/-- Transitivity: from `a = b` and `b = c`, `a = c`, by `LL` at `λz. a = z`. -/
theorem eqTrans {σ : Ty} {a b c : Term Sig Γ σ} (h₁ : Derivable Ax Δ (Term.eq' a b))
    (h₂ : Derivable Ax Δ (Term.eq' b c)) : Derivable Ax Δ (Term.eq' a c) :=
  have h : Derivable Ax Δ (.app (.lam (Term.eq' a.weaken (.var .zero))) c) :=
    ll (.lam (Term.eq' a.weaken (.var .zero))) h₂ (conv h₁ (Conv.symm (by
      have := Conv.beta' (Sig := Sig) (Γ := Γ) (Term.eq' a.weaken (.var .zero)) b
      simpa [Term.instantiate, Term.subst_rename, Term.subst_id] using this)))
  conv h (by
    have := Conv.beta' (Sig := Sig) (Γ := Γ) (Term.eq' a.weaken (.var .zero)) c
    simpa [Term.instantiate, Term.subst_rename, Term.subst_id] using this)

/-- Congruence: from `a = b`, `F a = F b`, by `LL` at `λz. F a = F z`. This is Lean's
`congrArg`. -/
theorem eqCongr {σ : Ty} {ρ : RTy} (F : Term Sig Γ (σ ⇒ ρ)) {a b : Term Sig Γ σ}
    (h : Derivable Ax Δ (Term.eq' a b)) :
    Derivable Ax Δ (Term.eq' (.app F a) (.app F b)) :=
  have h' : Derivable Ax Δ (.app (.lam (Term.eq' (.app F.weaken a.weaken) (.app F.weaken (.var .zero)))) b) :=
    ll _ h (conv (refl (.app F a)) (Conv.symm (by
      have := Conv.beta' (Sig := Sig) (Γ := Γ)
        (Term.eq' (.app F.weaken a.weaken) (.app F.weaken (.var .zero))) a
      simpa [Term.instantiate, Term.subst_rename, Term.subst_id] using this)))
  conv h' (by
    have := Conv.beta' (Sig := Sig) (Γ := Γ)
      (Term.eq' (.app F.weaken a.weaken) (.app F.weaken (.var .zero))) b
    simpa [Term.instantiate, Term.subst_rename, Term.subst_id] using this)

/-- From `f = g`, `f a = g a`, by `LL` at `λz. f a = z a`. This is Lean's `congrFun`. -/
theorem eqCongrFun {σ : Ty} {ρ : RTy} {f g : Term Sig Γ (σ ⇒ ρ)}
    (h : Derivable Ax Δ (Term.eq' f g)) (a : Term Sig Γ σ) :
    Derivable Ax Δ (Term.eq' (.app f a) (.app g a)) :=
  have h' : Derivable Ax Δ (.app (.lam (Term.eq' (.app f.weaken a.weaken) (.app (.var .zero) a.weaken))) g) :=
    ll _ h (conv (refl (.app f a)) (Conv.symm (by
      have := Conv.beta' (Sig := Sig) (Γ := Γ)
        (Term.eq' (.app f.weaken a.weaken) (.app (.var .zero) a.weaken)) f
      simpa [Term.instantiate, Term.subst_rename, Term.subst_id] using this)))
  conv h' (by
    have := Conv.beta' (Sig := Sig) (Γ := Γ)
      (Term.eq' (.app f.weaken a.weaken) (.app (.var .zero) a.weaken)) g
    simpa [Term.instantiate, Term.subst_rename, Term.subst_id] using this)

/-- From `p = q` and `p`, `q`: `LL` at the identity predicate `λz. z`. Lean's `Eq.mp`. -/
theorem eqMp {p q : Formula Sig Γ} (h : Derivable Ax Δ (Term.eq' p q)) (hp : Derivable Ax Δ p) :
    Derivable Ax Δ q :=
  conv (ll (.lam (.var .zero)) h (conv hp (Conv.symm (Conv.beta' (.var .zero) p))))
    (Conv.beta' (.var .zero) q)

/-- From `p = q` and `q`, `p`. Lean's `Eq.mpr`. -/
theorem eqMpr {p q : Formula Sig Γ} (h : Derivable Ax Δ (Term.eq' p q)) (hq : Derivable Ax Δ q) :
    Derivable Ax Δ p :=
  eqMp (eqSymm h) hq

/-! ### Substitution of provably identical terms, at any depth

`LL` substitutes at the top of a formula; Subst, with its hole under binders, substitutes
logically equivalent *formulas* anywhere. By induction on the type the two combine into
substitution of provably identical *terms* of any type, anywhere: a closed derivation of
`A = B` in the logical part of the theory licenses replacing `A` by `B` under binders. At
`t` this is Subst, the two premises got from the identity by `LL`; at `τ → ρ` the identity
is instantiated at a fresh variable, the induction hypothesis is applied at `ρ` with the
hole moved under an abstraction, and η closes both ends. This is the paper's ξ, and what
Lean's `funext` on a closed proof comes to. -/

theorem substEq {Ax : AxiomSet Sig} : ∀ (ρ : RTy) {Γ Γ' : Ctx} {Δ : List (Formula Sig Γ)}
    (K : Hole Sig Γ Ty.t Γ' (Ty.rel ρ)) {A B : Term Sig Γ' ρ},
    Derivable Ax.logical [] (Term.eq' A B) → Derivable Ax Δ (K.plug A) → Derivable Ax Δ (K.plug B) := by
  intro ρ
  induction ρ using RTy.induction with
  | t =>
    intro Γ Γ' Δ K A B h hK
    exact subst K (eqMp (weaken₁ h) hyp₀) (eqMpr (weaken₁ h) hyp₀) hK
  | arr τ ρ ih =>
    intro Γ Γ' Δ K A B h hK
    -- the identity, instantiated at a fresh variable
    have h' : Derivable Ax.logical []
        (Term.eq' (Term.app A.weaken (.var .zero)) (Term.app B.weaken (.var .zero))) :=
      eqCongrFun (rename (Ren.shift (σ := τ)) h) (.var .zero)
    -- the hole, moved under an abstraction: `K[λv. ⬚]`
    have hK' : Derivable Ax Δ ((K.comp (Hole.lam Hole.hole)).plug (Term.app A.weaken (.var .zero))) := by
      rw [Hole.plug_comp]
      exact conv hK (Hole.plug_conv K (Conv.symm (Conv.eta A)))
    have := ih (K.comp (Hole.lam Hole.hole)) h' hK'
    rw [Hole.plug_comp] at this
    exact conv this (Hole.plug_conv K (Conv.eta B))

/-! ### The same rules, with the β-redex contracted

Lean's typing of an application substitutes, so the type of `h a` is the instantiated
body, where the rule `allE` yields the application `F a`. These variants conclude with
`instantiate`, which computes to the same tree the quoter reads from Lean's type, so no
conversion step is needed at the use site; the kernel evaluates the substitution. -/

theorem allEβ {σ : Ty} {b : Formula Sig (σ :: Γ)} (h : Derivable Ax Δ (Term.forall' b))
    (a : Term Sig Γ σ) : Derivable Ax Δ (b.instantiate a) :=
  conv (allE h a) (Conv.beta' b a)

theorem exIβ {σ : Ty} {b : Formula Sig (σ :: Γ)} (a : Term Sig Γ σ)
    (h : Derivable Ax Δ (b.instantiate a)) : Derivable Ax Δ (Term.exists' b) :=
  exI a (conv h (Conv.symm (Conv.beta' b a)))

theorem llβ {σ : Ty} {a b : Term Sig Γ σ} (P : Formula Sig (σ :: Γ))
    (h₁ : Derivable Ax Δ (Term.eq' a b)) (h₂ : Derivable Ax Δ (P.instantiate a)) :
    Derivable Ax Δ (P.instantiate b) :=
  conv (ll (.lam P) h₁ (conv h₂ (Conv.symm (Conv.beta' P a)))) (Conv.beta' P b)

theorem eqCongrβ {σ : Ty} {ρ : RTy} (B : Term Sig (σ :: Γ) ρ) {a b : Term Sig Γ σ}
    (h : Derivable Ax Δ (Term.eq' a b)) :
    Derivable Ax Δ (Term.eq' (B.instantiate a) (B.instantiate b)) :=
  have h' := eqCongr (.lam B) h
  conv h' (Conv.app_congr (Conv.app_congr (Conv.refl _) (Conv.beta' B a)) (Conv.beta' B b))

theorem eqCongrFunβ {σ : Ty} {ρ : RTy} {b₁ b₂ : Term Sig (σ :: Γ) ρ}
    (h : Derivable Ax Δ (Term.eq' (Term.lam b₁) (Term.lam b₂))) (a : Term Sig Γ σ) :
    Derivable Ax Δ (Term.eq' (b₁.instantiate a) (b₂.instantiate a)) :=
  have h' := eqCongrFun h a
  conv h' (Conv.app_congr (Conv.app_congr (Conv.refl _) (Conv.beta' b₁ a)) (Conv.beta' b₂ a))

end Derivable

end Classicism.Meta
