import Classicism.Core
import Classicism.Equivalence
import Classicism.Booleanism
import Classicism.Identities
import Classicism.Axiomatization
import Classicism.Algebra
import Classicism.Strict
import Classicism.Tautology
import Classicism.Quantifier
import Classicism.Rules
import Classicism.Primitives
import Classicism.Transform
import Classicism.Modal
import Classicism.Order
import Classicism.Comprehension
import Classicism.Mirror
import Classicism.Principles
import Classicism.Proofs
import Classicism.Transformed
import Classicism.Check
import Classicism.TypeSystem
import Classicism.Audit
import Classicism.Tests
import Classicism.Meta.Types
import Classicism.Meta.Term
import Classicism.Meta.Conversion
import Classicism.Meta.Derivation
import Classicism.Meta.Axioms
import Classicism.Meta.Examples
