import Classicism.Core
import Classicism.Equivalence
import Classicism.Booleanism
import Classicism.Identities
import Classicism.Axiomatization
import Classicism.Algebra
import Classicism.Strict
import Classicism.Tautology
import Classicism.Quantifier
import Classicism.Rules
import Classicism.Primitives
import Classicism.Transform
import Classicism.Modal
import Classicism.Order
import Classicism.Comprehension
import Classicism.Principles
import Classicism.Proofs
import Classicism.Check
import Classicism.TypeSystem
import Classicism.Audit
import Classicism.Tests
