import Classicism.Core
import Classicism.Equivalence
import Classicism.Booleanism
import Classicism.Identities
import Classicism.Axiomatization
import Classicism.Algebra
import Classicism.Strict
import Classicism.Tautology
import Classicism.Quantifier
import Classicism.Rules
import Classicism.Primitives
import Classicism.Transform
import Classicism.Modal
import Classicism.Order
import Classicism.Comprehension
import Classicism.Mirror
import Classicism.Principles
import Classicism.Proofs
import Classicism.Transformed
import Classicism.Check
import Classicism.TypeSystem
import Classicism.Audit
import Classicism.Tests
import Classicism.Meta.Types
import Classicism.Meta.Term
import Classicism.Meta.Conversion
import Classicism.Meta.Derivation
import Classicism.Meta.Axioms
import Classicism.Meta.Entailment
import Classicism.Meta.SyntaxSchemas
import Classicism.Meta.Denotation
import Classicism.Meta.Relational
import Classicism.Meta.Quote
import Classicism.Meta.Quoted
import Classicism.Meta.Normalize
import Classicism.Meta.Translate
import Classicism.Meta.Derived
import Classicism.Meta.Schema
import Classicism.Meta.Schemas
import Classicism.Meta.Examples
import Classicism.Meta.Action
import Classicism.Meta.ActionSoundness
import Classicism.Meta.ActionFull
import Classicism.Meta.ActionFacts
import Classicism.Meta.ActionExamples
import Classicism.Meta.ActionProperties
