import Classicism.Certified.Entailed
import Classicism.Syntax.VectorizeDerivable

/-!
# Checks: the map's principles at lists of types

The list forms generated by `#classicism_schema` (`Certified/Schemas.lean`), on three
principles of different shapes (Barcan, with a Ty-parameter only; Functionality, with a
relational codomain; Relational Choice, vectorized in its input, its output a single
type), at the empty list, at one-element lists and at a two-element list, each checked by
`rfl` against the sentence written out by hand; and a record's list form, generated by
`#classicism_entails_audit` (`Certified/Entailed.lean`) from the vectorization theorem,
at the same lists.

The checks are stated outside the namespace `Classicism`, so that the object language's
`imp` and the rest can be used unqualified without meeting the shallow layer's.
-/

namespace Classicism.Meta.VectorizeChecks

/-- Two more short names for variables. -/
abbrev v3 {Sig : Signature} {Γ : Ctx} {σ τ υ ω : Ty} : Term Sig (ω :: υ :: τ :: σ :: Γ) σ :=
  .var (.succ (.succ (.succ .zero)))
@[inherit_doc v3] abbrev v4 {Sig : Signature} {Γ : Ctx} {σ τ υ ω ψ : Ty} :
    Term Sig (ψ :: ω :: υ :: τ :: σ :: Γ) σ :=
  .var (.succ (.succ (.succ (.succ .zero))))

end Classicism.Meta.VectorizeChecks

section
open Classicism hiding imp iff
open Classicism.Meta Classicism.Meta.Term Classicism.Meta.VectorizeChecks

/-! ### A one-element list is the type itself, on the nose -/

example (σ : Ty) : P.Barcan.listQuoted [σ] = P.Barcan.quoted σ := rfl
example (σ : Ty) : P.Functionality.listQuoted [σ] .t = P.Functionality.quoted σ .t :=
  rfl
example (σ : Ty) :
    P.RelationalChoice.listQuoted [σ] .e = P.RelationalChoice.quoted σ .e := rfl

/-! ### The empty list -/

/-- BF over no variables: `∀X:t. □X → □X`. -/
example : P.Barcan.listQuoted [] = forall' (σ := Ty.t) (imp (box v0) (box v0)) := rfl

/-- Functionality over no variables, into `t`: `∀X Y:t. X = Y → X = Y`. -/
example : P.Functionality.listQuoted [] .t
    = forall' (σ := Ty.t) (forall' (σ := Ty.t) (imp (eq' v1 v0) (eq' v1 v0))) := rfl

/-- Relational Choice from no inputs, into `e`: every instantiated property of individuals
has a subproperty with exactly one instance. -/
example : P.RelationalChoice.listQuoted [] .e
    = forall' (σ := Ty.rel (Ty.e ⇒ .t)) (imp (exists' (σ := Ty.e) (app v1 v0))
        (exists' (σ := Ty.rel (Ty.e ⇒ .t)) (conj
          (exists' (σ := Ty.e) (conj (app v1 v0)
            (forall' (σ := Ty.e) (imp (app v2 v0) (eq' v1 v0)))))
          (forall' (σ := Ty.e) (imp (app v1 v0) (app v2 v0)))))) := rfl

/-! ### A two-element list -/

/-- BF over `x₁:e, x₂:t`: `∀X. (∀x₁ x₂. □X x₁ x₂) → □∀x₁ x₂. X x₁ x₂`. -/
example : P.Barcan.listQuoted [.e, .t]
    = forall' (σ := Ty.rel (Ty.e ⇒ Ty.t ⇒ .t)) (imp
        (forall' (σ := Ty.e) (forall' (σ := Ty.t) (box (app (app v2 v1) v0))))
        (box (forall' (σ := Ty.e) (forall' (σ := Ty.t) (app (app v2 v1) v0))))) := rfl

/-- Functionality over `x₁:e, x₂:t`, into `t`: `∀X Y. (∀z₁ z₂. X z₁ z₂ = Y z₁ z₂) → X = Y`. -/
example : P.Functionality.listQuoted [.e, .t] .t
    = forall' (σ := Ty.rel (Ty.e ⇒ Ty.t ⇒ .t)) (forall' (σ := Ty.rel (Ty.e ⇒ Ty.t ⇒ .t)) (imp
        (forall' (σ := Ty.e) (forall' (σ := Ty.t) (eq' (app (app v3 v1) v0) (app (app v2 v1) v0))))
        (eq' v1 v0))) := rfl

/-- Relational Choice from `x₁:e, x₂:t`, into `e`. -/
example : P.RelationalChoice.listQuoted [.e, .t] .e
    = forall' (σ := Ty.rel (Ty.e ⇒ Ty.t ⇒ Ty.e ⇒ .t)) (imp
        (forall' (σ := Ty.e) (forall' (σ := Ty.t)
          (exists' (σ := Ty.e) (app (app (app v3 v2) v1) v0))))
        (exists' (σ := Ty.rel (Ty.e ⇒ Ty.t ⇒ Ty.e ⇒ .t)) (conj
          (forall' (σ := Ty.e) (forall' (σ := Ty.t) (exists' (σ := Ty.e) (conj
            (app (app (app v3 v2) v1) v0)
            (forall' (σ := Ty.e) (imp (app (app (app v4 v3) v2) v0) (eq' v1 v0)))))))
          (forall' (σ := Ty.e) (forall' (σ := Ty.t) (forall' (σ := Ty.e)
            (imp (app (app (app v3 v2) v1) v0) (app (app (app v4 v2) v1) v0)))))))) := rfl

/-! ### A record's list form

`barcan_r_implies_functionality_r` is derived in `C⁻` at every pair of types, so at
`var 0`, and vectorizing that derivation gives its list rule, at every list. -/

/-- At the empty list. -/
example : C.Theorem (Sig := Signature.pure) (imp
    (forall' (σ := Ty.t) (imp (box v0) (box v0)))
    (forall' (σ := Ty.t) (forall' (σ := Ty.t) (imp (eq' v1 v0) (eq' v1 v0))))) :=
  Proofs.barcan_r_implies_functionality_r.listRule [] .t trivial

/-- At `[e, t]`. -/
example : C.Theorem (Sig := Signature.pure) (imp
    (forall' (σ := Ty.rel (Ty.e ⇒ Ty.t ⇒ .t)) (imp
      (forall' (σ := Ty.e) (forall' (σ := Ty.t) (box (app (app v2 v1) v0))))
      (box (forall' (σ := Ty.e) (forall' (σ := Ty.t) (app (app v2 v1) v0))))))
    (forall' (σ := Ty.rel (Ty.e ⇒ Ty.t ⇒ .t)) (forall' (σ := Ty.rel (Ty.e ⇒ Ty.t ⇒ .t)) (imp
      (forall' (σ := Ty.e) (forall' (σ := Ty.t) (eq' (app (app v3 v1) v0) (app (app v2 v1) v0))))
      (eq' v1 v0))))) :=
  Proofs.barcan_r_implies_functionality_r.listRule [.e, .t] .t trivial

/-- At a one-element list, the restricted arrow itself. -/
example (σ : Ty) : C.Theorem (imp (P.Barcan.quoted σ) (P.Functionality.quoted σ .t)) :=
  Proofs.barcan_r_implies_functionality_r.listRule [σ] .t trivial

/-- And the arrow between the list schemas. -/
example : P.Barcan.listSchema ⟹ P.Functionality.listSchema :=
  Proofs.barcan_r_implies_functionality_r.listEntails

end
