import Classicism.MapModels
import Classicism.Models.Conditions

/-!
# The map's general arguments, certified

A general argument on the map says that every model meeting some conditions has a verdict.
Here each verdict of an argument proved in Lean is one theorem, named
`Arguments.<argument id>.<principle id>` (a topic's argument, `arguments/<id>.yaml`) or
`Arguments.<group id>.<argument id>.<principle id>` (a group's shared argument), whose type is
the statement the map generates for it (`Classicism/ModelStatements.lean`):

- a topic's argument: for every intensional action model meeting the conditions, each the
  Lean predicate named in `conditions.yaml` (`Models/Conditions.lean`), the verdict;
- a group's argument: for every value of what the group's construction is built from (for the
  finite-support models on one object, a monoid acting faithfully on `ℕ`) meeting the group's
  conditions, the verdict in the model built from it.

A model then gets the argument's verdict by applying the certificate to its proofs of the
conditions: `MapDerived.lean`, generated by the map, for every model the map gives the argument.
-/

namespace Classicism.Map.Arguments

open CategoryTheory Meta Meta.Intensional Meta.Intensional.Premodel Meta.Intensional.MonoidModel

/-! ## Arguments of the topic -/

namespace no_pure_contingency_one_object

/-- In a model with one object, a true pure sentence is necessary (`Premodel.holdsAx_npc`). -/
theorem no_pure_contingency_r :
    Statements.Arguments.no_pure_contingency_one_object.no_pure_contingency_r := by
  intro Sig C _ A M hone
  rw [← AxiomSet.npc_eq_pureVersion]
  exact A.holdsAx_npc M

end no_pure_contingency_one_object

namespace barcan_d6

/-- Proposition D.6: in an ideally full model whose arrows out of the evaluation object are
surjective on the individuals, `BF_σ` at every type (`Premodel.ideal_bf_of_surjective`), read
in the pure reduct. -/
theorem barcan_r : Statements.Arguments.barcan_d6.barcan_r := by
  rintro Sig C _ A - ⟨W₀, De, ne, I, rfl, hs⟩
  rw [holdsAx_ofPure, reduct_ideal]
  rintro _ ⟨σ, -, rfl⟩
  exact Premodel.ideal_bf_of_surjective De hs σ

end barcan_d6

namespace relational_choice_full

/-- Relational Choice holds in every extensionally full model (`Premodel.holds_rc`), so in every
full one. -/
theorem relational_choice_r : Statements.Arguments.relational_choice_full.relational_choice_r := by
  intro Sig C _ A M hF _
  rw [holdsAx_ofPure]
  rintro _ ⟨σ, τ, -, -, rfl⟩
  exact holds_rc (A.reduct_isModel M) (Full.extFull A hF) (𝟙 _) σ τ

end relational_choice_full

namespace relational_choice_full_boxed

/-- And at every arrow of a full model (`Premodel.holds_box_rc`). -/
theorem necessary_relational_choice_r :
    Statements.Arguments.relational_choice_full_boxed.necessary_relational_choice_r := by
  intro Sig C _ A M hF _
  rw [holdsAx_ofPure]
  rintro _ ⟨σ, τ, -, -, rfl⟩
  exact holds_box_rc (A.reduct_isModel M) (Full.extFull A hF) (𝟙 _) σ τ

end relational_choice_full_boxed

namespace transversal_choice_extensionally_full

/-- Transversal Choice holds in every extensionally full model (`Premodel.holds_tc`). -/
theorem transversal_choice_r :
    Statements.Arguments.transversal_choice_extensionally_full.transversal_choice_r := by
  intro Sig C _ A M hE _
  rw [holdsAx_ofPure]
  rintro _ ⟨σ, -, rfl⟩
  exact holds_tc (A.reduct_isModel M) hE (𝟙 _) σ

end transversal_choice_extensionally_full

namespace dpc_isolated_actual_world

/-- Distinctness-Preserving Collapse holds where the actual world is isolated
(`Premodel.holds_dpc`). -/
theorem distinctness_preserving_collapse :
    Statements.Arguments.dpc_isolated_actual_world.distinctness_preserving_collapse := by
  intro Sig C _ A M hI
  rw [holdsAx_ofPure]
  rintro _ rfl
  exact holds_dpc (A.reduct_isModel M) hI

end dpc_isolated_actual_world

/-! ## Arguments of the finite-support models on one object -/

namespace finite_support_one_object

namespace actual_world

/-- The actual-world proposition is in the domain (`actuality_of_pinned_one`). -/
theorem actuality : Statements.Arguments.finite_support_one_object.actual_world.actuality :=
  fun M _ _ _ h => verdict_holds (model_isModel M) (holdsAx_eq.2 (actuality_of_pinned_one M h)) |>.2

end actual_world

namespace collapsing_atomless

theorem atomicity_t : Statements.Arguments.finite_support_one_object.collapsing_atomless.atomicity_t :=
  fun M _ _ _ h => verdict_fails (model_isModel M)
    (not_holdsAx_of (Ax := P.AtomicityT.schema) rfl (not_atomicityT_of_collapseUnpinned M h)) |>.2

theorem atomicity_r : Statements.Arguments.finite_support_one_object.collapsing_atomless.atomicity_r :=
  fun M _ _ _ h => verdict_fails (model_isModel M)
    (not_holdsAx_of (Ax := P.Atomicity.schema) (a := P.Atomicity.quoted .t) ⟨.t, by simp, rfl⟩
      (not_atomicityT_of_collapseUnpinned M h)) |>.2

end collapsing_atomless

namespace barcan_positive

/-- The property of being positive: an arrow sending `0` to a positive number sends
everything there, being monotone, but some arrow does so while `0` is not positive
(`MonoidModel.not_bf_e`). -/
theorem barcan_r : Statements.Arguments.finite_support_one_object.barcan_positive.barcan_r :=
  fun M _ _ _ ⟨hmono, g, hg⟩ => verdict_fails (model_isModel M) (not_holdsAx_of ⟨.e, trivial, rfl⟩
    (not_bf_e M (· ≠ 0) (· ≠ 0) 0
      (fun k y hk => by have := hmono k (Nat.zero_le y); simp only at this; omega)
      ⟨g, hg.ne', 0, by simp⟩)) |>.2

end barcan_positive

end finite_support_one_object

end Classicism.Map.Arguments
