import Classicism.MapModels
import Classicism.Models.Conditions
import Classicism.Semantics.OneIndividual
import Classicism.Semantics.Interpretations
import Classicism.Models.SymBase
import Mathlib.SetTheory.Cardinal.NatCard

/-!
# The map's general arguments, certified

A general argument on the map says that every model meeting some conditions has a verdict.
Here each verdict of an argument proved in Lean is one theorem, named
`Arguments.<argument id>.<principle id>` (a topic's argument, `arguments/<id>.yaml`) or
`Arguments.<group id>.<argument id>.<principle id>` (a group's shared argument), whose type is
the statement the map generates for it (`Classicism/ModelStatements.lean`):

- a topic's argument: for every intensional action model meeting the conditions, each the
  Lean predicate named in `conditions.yaml` (`Models/Conditions.lean`), the verdict;
- a group's argument: for every value of what the group's construction is built from (for the
  finite-support models on one object, a monoid acting faithfully on `ℕ`) meeting the group's
  conditions, the verdict in the model built from it.

A model then gets the argument's verdict by applying the certificate to its proofs of the
conditions: `MapDerived.lean`, generated by the map, for every model the map gives the argument.
-/

namespace Classicism.Map.Arguments

open CategoryTheory Meta Meta.Intensional Meta.Intensional.Premodel Meta.Intensional.MonoidModel

/-! ## Arguments of the topic -/

namespace no_pure_contingency_one_object

/-- In a model with one object, a true pure sentence is necessary (`Premodel.holdsAx_npc`). -/
theorem no_pure_contingency_r :
    Statements.Arguments.no_pure_contingency_one_object.no_pure_contingency_r := by
  intro Sig C _ A M hone
  rw [← AxiomSet.npc_eq_pureVersion]
  exact A.holdsAx_npc M

end no_pure_contingency_one_object

namespace barcan_d6

/-- Proposition D.6: in an ideally full model whose arrows out of the evaluation object are
surjective on the individuals, `BF_σ` at every type (`Premodel.ideal_bf_of_surjective`), read
in the pure reduct. -/
theorem barcan_r : Statements.Arguments.barcan_d6.barcan_r := by
  rintro Sig C _ A - ⟨W₀, De, ne, I, rfl, hs⟩
  rw [holdsAx_ofPure, reduct_ideal]
  rintro _ ⟨σ, -, rfl⟩
  exact Premodel.ideal_bf_of_surjective De hs σ

end barcan_d6

namespace relational_choice_full

/-- Relational Choice holds in every extensionally full model (`Premodel.holds_rc`), so in every
full one. -/
theorem relational_choice_r : Statements.Arguments.relational_choice_full.relational_choice_r := by
  intro Sig C _ A M hF _
  rw [holdsAx_ofPure]
  rintro _ ⟨σ, τ, -, -, rfl⟩
  exact holds_rc (A.reduct_isModel M) (Full.extFull A hF) (𝟙 _) σ τ

end relational_choice_full

namespace relational_choice_full_boxed

/-- And at every arrow of a full model (`Premodel.holds_box_rc`). -/
theorem necessary_relational_choice_r :
    Statements.Arguments.relational_choice_full_boxed.necessary_relational_choice_r := by
  intro Sig C _ A M hF _
  rw [holdsAx_ofPure]
  rintro _ ⟨σ, τ, -, -, rfl⟩
  exact holds_box_rc (A.reduct_isModel M) (Full.extFull A hF) (𝟙 _) σ τ

end relational_choice_full_boxed

namespace transversal_choice_extensionally_full

/-- Transversal Choice holds in every extensionally full model (`Premodel.holds_tc`). -/
theorem transversal_choice_r :
    Statements.Arguments.transversal_choice_extensionally_full.transversal_choice_r := by
  intro Sig C _ A M hE _
  rw [holdsAx_ofPure]
  rintro _ ⟨σ, -, rfl⟩
  exact holds_tc (A.reduct_isModel M) hE (𝟙 _) σ

end transversal_choice_extensionally_full

namespace dpc_isolated_actual_world

/-- Distinctness-Preserving Collapse holds where the actual world is isolated
(`Premodel.holds_dpc`). -/
theorem distinctness_preserving_collapse :
    Statements.Arguments.dpc_isolated_actual_world.distinctness_preserving_collapse := by
  intro Sig C _ A M hI
  rw [holdsAx_ofPure]
  rintro _ rfl
  exact holds_dpc (A.reduct_isModel M) hI

end dpc_isolated_actual_world

namespace one_individual

/-- With one individual there are no two distinct ones: the second instance of the Infinity
schema at `e` fails (`Premodel.holds_count`). -/
theorem infinity_e : Statements.Arguments.one_individual.infinity_e := by
  intro Sig C _ A M h1 H
  rw [holdsAx_ofPure] at H
  obtain ⟨f, hf⟩ := (holds_count (A.reduct_isModel M) (𝟙 _) .e 2).1 (H _ ⟨2, by decide, rfl⟩)
  haveI : Subsingleton (A.reduct.Dom A.reduct.W₀ .e) := h1 A.W₀
  exact absurd (hf (Subsingleton.elim (f 0) (f 1))) (by decide)

/-- `Suc_e 𝟎_e` is a finite cardinality holding of the universal property
(`Premodel.not_holds_axiomOfInfinityE`). -/
theorem axiom_of_infinity_e : Statements.Arguments.one_individual.axiom_of_infinity_e := by
  intro Sig C _ A M h1 H
  rw [holdsAx_ofPure] at H
  exact not_holds_axiomOfInfinityE (A.reduct_isModel M) (𝟙 _) (h1 A.W₀) (H _ rfl)

/-- And so at every world (`Premodel.not_holds_possibleInfinityE`). -/
theorem possible_infinity_e : Statements.Arguments.one_individual.possible_infinity_e := by
  intro Sig C _ A M h1 H
  rw [holdsAx_ofPure] at H
  exact not_holds_possibleInfinityE (A.reduct_isModel M) (𝟙 _) h1 (H _ rfl)

end one_individual

namespace finitely_many_propositions

/-- With `k` propositions there are no `k + 1` distinct ones: that instance of the Infinity
schema at `t` fails (`Premodel.holds_count`). -/
theorem infinity_t : Statements.Arguments.finitely_many_propositions.infinity_t := by
  intro Sig C _ A M _ hfin H
  have : Finite (A.reduct.Dom A.reduct.W₀ (.rel .t)) := hfin
  rw [holdsAx_ofPure] at H
  obtain ⟨f, hf⟩ := (holds_count (A.reduct_isModel M) (𝟙 _) (.rel .t)
    (Nat.card (A.reduct.Dom A.reduct.W₀ (.rel .t)) + 1)).1
    (H _ ⟨_, Nat.le_add_left 1 _, rfl⟩)
  have := Nat.card_le_card_of_injective f hf
  simp at this

/-- The numeral counting the propositions holds of the universal property
(`Premodel.not_holds_axInf_of_finite`). -/
theorem axiom_of_infinity_t : Statements.Arguments.finitely_many_propositions.axiom_of_infinity_t := by
  intro Sig C _ A M _ hfin H
  have : Finite (A.reduct.Dom A.reduct.W₀ (.rel .t)) := hfin
  rw [holdsAx_ofPure] at H
  exact not_holds_axInf_of_finite (A.reduct_isModel M) (𝟙 _) (.rel .t) (H _ rfl)

end finitely_many_propositions

namespace finitely_many_propositions_everywhere

/-- At every world the numeral counting the propositions holds of the universal property
(`Premodel.not_holds_dia_axInf_of_finite`). -/
theorem possible_infinity_t :
    Statements.Arguments.finitely_many_propositions_everywhere.possible_infinity_t := by
  intro Sig C _ A M hfin H
  rw [holdsAx_ofPure] at H
  exact not_holds_dia_axInf_of_finite (A.reduct_isModel M) (𝟙 _) (.rel .t)
    (fun k => hfin (𝟙 _ ≫ k)) (H _ rfl)

end finitely_many_propositions_everywhere

namespace infinitely_many_individuals

/-- The property of holding only of finite properties is in the domain
(`Premodel.holds_axInf_of_infinite`). -/
theorem axiom_of_infinity_e : Statements.Arguments.infinitely_many_individuals.axiom_of_infinity_e := by
  intro Sig C _ A M hE hinf
  have : Infinite (A.reduct.Dom A.reduct.W₀ .e) := hinf
  rw [holdsAx_ofPure]
  rintro _ rfl
  exact holds_axInf_of_infinite (A.reduct_isModel M) hE (𝟙 _) .e

theorem infinity_e : Statements.Arguments.infinitely_many_individuals.infinity_e := by
  intro Sig C _ A M _ hinf
  have : Infinite (A.reduct.Dom A.reduct.W₀ .e) := hinf
  rw [holdsAx_ofPure]
  rintro _ ⟨n, -, rfl⟩
  exact holds_count_of_infinite (A.reduct_isModel M) (𝟙 _) .e n

end infinitely_many_individuals

namespace infinitely_many_propositions

theorem axiom_of_infinity_t : Statements.Arguments.infinitely_many_propositions.axiom_of_infinity_t := by
  intro Sig C _ A M hE hinf
  have : Infinite (A.reduct.Dom A.reduct.W₀ (.rel .t)) := hinf
  rw [holdsAx_ofPure]
  rintro _ rfl
  exact holds_axInf_of_infinite (A.reduct_isModel M) hE (𝟙 _) (.rel .t)

theorem infinity_t : Statements.Arguments.infinitely_many_propositions.infinity_t := by
  intro Sig C _ A M _ hinf
  have : Infinite (A.reduct.Dom A.reduct.W₀ (.rel .t)) := hinf
  rw [holdsAx_ofPure]
  rintro _ ⟨n, -, rfl⟩
  exact holds_count_of_infinite (A.reduct_isModel M) (𝟙 _) (.rel .t) n

end infinitely_many_propositions

namespace full_atomicity

/-- Atomicity holds at every arrow of a full model (`Premodel.holds_box_atomicity`). -/
theorem necessary_atomicity_r : Statements.Arguments.full_atomicity.necessary_atomicity_r := by
  intro Sig C _ A M hF
  rw [holdsAx_ofPure]
  rintro _ ⟨ρ, -, rfl⟩
  exact holds_box_atomicity (A.reduct_isModel M) hF (𝟙 _) ρ

end full_atomicity

namespace full_rigid_comprehension

/-- Rigid Comprehension holds at every arrow of a full model
(`Premodel.holds_box_rigid_comprehension`). -/
theorem necessary_rigid_comprehension_r :
    Statements.Arguments.full_rigid_comprehension.necessary_rigid_comprehension_r := by
  intro Sig C _ A M hF
  rw [holdsAx_ofPure]
  rintro _ ⟨ρ, -, rfl⟩
  exact holds_box_rigid_comprehension (A.reduct_isModel M) hF (𝟙 _) ρ

end full_rigid_comprehension

namespace full_epic_barcan

/-- `BF` at every world of a full model whose arrows are epimorphisms acting surjectively on the
individuals (`Premodel.holds_box_bf_of_epic`). -/
theorem necessary_barcan_r : Statements.Arguments.full_epic_barcan.necessary_barcan_r := by
  intro Sig C _ A M hF hE
  rw [holdsAx_ofPure]
  rintro _ ⟨σ, hσ, rfl⟩
  exact holds_box_bf_of_epic (A.reduct_isModel M) hF hE (𝟙 _) σ hσ

end full_epic_barcan

namespace invertible_arrows

theorem necessary_distinctness_necessary_r :
    Statements.Arguments.invertible_arrows.necessary_distinctness_necessary_r := by
  intro Sig C _ A M hI
  rw [holdsAx_ofPure]
  rintro _ ⟨σ, -, rfl⟩
  exact holds_box_nd_of_invertible (A.reduct_isModel M) hI (𝟙 _) σ

theorem necessary_barcan_r : Statements.Arguments.invertible_arrows.necessary_barcan_r := by
  intro Sig C _ A M hI
  rw [holdsAx_ofPure]
  rintro _ ⟨σ, -, rfl⟩
  exact holds_box_bf_of_invertible (A.reduct_isModel M) hI (𝟙 _) σ

end invertible_arrows

namespace retractions

theorem distinctness_necessary_r : Statements.Arguments.retractions.distinctness_necessary_r := by
  intro Sig C _ A M hr
  rw [holdsAx_ofPure]
  rintro _ ⟨σ, -, rfl⟩
  exact holds_nd_of_retractions (A.reduct_isModel M) hr σ

end retractions

namespace unretracted_arrow

theorem distinctness_necessary_t : Statements.Arguments.unretracted_arrow.distinctness_necessary_t := by
  intro Sig C _ A M hF hU H
  rw [holdsAx_ofPure] at H
  exact not_holds_nd_t_of_unretracted (A.reduct_isModel M) hF hU (H _ rfl)

end unretracted_arrow

namespace nonidentity_arrow

theorem fregean_axiom : Statements.Arguments.nonidentity_arrow.fregean_axiom := by
  intro Sig C _ A M hF ⟨V, k, hk⟩ H
  rw [holdsAx_ofPure] at H
  exact A.reduct.not_fregean_of_propFull (A.reduct_isModel M) (Full.propFull _ hF) k hk (H _ rfl)

end nonidentity_arrow

namespace nonepic_strong_leibniz

/-- The type-`t` Strong Leibniz Biconditionals fail in a full model with a non-epi arrow out of
the evaluation object (`Premodel.not_holds_strongLeibnizT_of_nonepic`). -/
theorem strong_leibniz_t : Statements.Arguments.nonepic_strong_leibniz.strong_leibniz_t := by
  intro Sig C _ A M hF hN H
  rw [holdsAx_ofPure] at H
  exact not_holds_strongLeibnizT_of_nonepic (A.reduct_isModel M) hF hN (H _ rfl)

end nonepic_strong_leibniz

namespace strong_actuality_unique_retractions

/-- Strong Actuality holds where the identity singletons are in the domain and the retractions
are unique, at the evaluation object and after it (`Premodel.holds_box_strongActuality_of_unique`). -/
theorem strong_actuality :
    Statements.Arguments.strong_actuality_unique_retractions.strong_actuality := by
  intro Sig C _ A M hI hU
  rw [holdsAx_ofPure]
  rintro _ rfl
  exact (holds_box_strongActuality_of_unique (A.reduct_isModel M) hI hU).1

/-- And its necessitation. -/
theorem necessary_strong_actuality :
    Statements.Arguments.strong_actuality_unique_retractions.necessary_strong_actuality := by
  intro Sig C _ A M hI hU
  rw [holdsAx_ofPure]
  rintro _ rfl
  exact (holds_box_strongActuality_of_unique (A.reduct_isModel M) hI hU).2

end strong_actuality_unique_retractions

namespace separated_retractions_strong_actuality

/-- Strong Actuality fails where an arrow out of the evaluation object has two retractions that
a proposition separates (`Premodel.not_holds_strongActuality_of_separated`). -/
theorem strong_actuality :
    Statements.Arguments.separated_retractions_strong_actuality.strong_actuality := by
  intro Sig C _ A M hS H
  rw [holdsAx_ofPure] at H
  exact not_holds_strongActuality_of_separated (A.reduct_isModel M) hS (H _ rfl)

end separated_retractions_strong_actuality

namespace dpc_returning_arrow

/-- Distinctness-Preserving Collapse fails in a full model where some arrow other than the
identity returns (`Premodel.not_holds_dpc_of_returning`). -/
theorem distinctness_preserving_collapse :
    Statements.Arguments.dpc_returning_arrow.distinctness_preserving_collapse := by
  intro Sig C _ A M hF hR H
  rw [holdsAx_ofPure] at H
  exact not_holds_dpc_of_returning (A.reduct_isModel M) hF hR (H _ rfl)

end dpc_returning_arrow

namespace coherent_retractions

/-- Gallin Extensional Comprehension holds in a full model with coherent retractions
(`Premodel.holds_gallin_of_coherent`). -/
theorem gallin_extensional_comprehension_r :
    Statements.Arguments.coherent_retractions.gallin_extensional_comprehension_r := by
  intro Sig C _ A M hF hR
  rw [holdsAx_ofPure]
  rintro _ ⟨ρ, -, rfl⟩
  exact holds_gallin_of_coherent (A.reduct_isModel M) hF hR ρ

end coherent_retractions

namespace fewer_propositions_after

/-- B for the pure sentence counting `n` propositions fails (`Premodel.not_holds_b_count`). -/
theorem pure_b_r : Statements.Arguments.fewer_propositions_after.pure_b_r := by
  intro Sig C _ A M hF H
  rw [holdsAx_ofPure] at H
  obtain ⟨n, hn⟩ := not_holds_b_count (A.reduct_isModel M) hF
  exact hn (H _ ⟨Count.closedTypes_b_count (by decide) n, _, rfl⟩)

end fewer_propositions_after

namespace sigma_top

/-- With `Σ` by tops, `c ≠ ⊤_ρ` is an instance of Independence that fails
(`Premodel.not_holdsAx_independence_of_sigmaTop`). -/
theorem independence_signature_r : Statements.Arguments.sigma_top.independence_signature_r :=
  fun _ M hS hT => not_holdsAx_independence_of_sigmaTop M hS hT

end sigma_top

namespace sigma_top_npc

/-- With `Σ` by tops, a sentence of `Σ` denotes what a pure sentence does, so No Pure
Contingency gives No Contingency relative to `Σ` (`Premodel.holdsAx_nc_of_sigmaTop`). -/
theorem no_contingency_signature_r : Statements.Arguments.sigma_top_npc.no_contingency_signature_r :=
  fun _ M _ hT hN => holdsAx_nc_of_sigmaTop M hT hN

end sigma_top_npc

/-! ## Arguments of the symmetric ideally full models -/

namespace symmetric_ideally_full

namespace relational_choice

/-- Relational Choice fails at `(e → t)` and `e` (`SymBase.not_rc_of_transposable`). -/
theorem relational_choice_r : Statements.Arguments.symmetric_ideally_full.relational_choice.relational_choice_r :=
  fun S h => verdict_fails S.model_isModel
    (not_holdsAx_of ⟨.rel (.arr .e .t), .e, ⟨trivial, trivial⟩, trivial, rfl⟩ (SymBase.not_rc_of_transposable h)) |>.2

end relational_choice

namespace actuality

/-- The symmetry group, finitely pinned, witnesses Actuality (`SymBase.actuality_of_pinned`). -/
theorem actuality : Statements.Arguments.symmetric_ideally_full.actuality.actuality :=
  fun S h => verdict_holds S.model_isModel (holdsAx_eq.2 (SymBase.actuality_of_pinned h)) |>.2

end actuality

namespace barcan_fixes_or_omits

/-- BF at `e` fails (`SymBase.not_bf_e_of_fixesOrOmits`). -/
theorem barcan_r : Statements.Arguments.symmetric_ideally_full.barcan_fixes_or_omits.barcan_r :=
  fun S h => verdict_fails S.model_isModel
    (not_holdsAx_of ⟨.e, trivial, rfl⟩ (SymBase.not_bf_e_of_fixesOrOmits h)) |>.2

end barcan_fixes_or_omits
namespace axiom_of_infinity_e

/-- The finite cardinalities' property is in the domain (`SymBase.holds_axInf`). -/
theorem axiom_of_infinity_e : Statements.Arguments.symmetric_ideally_full.axiom_of_infinity_e.axiom_of_infinity_e :=
  fun S h => by
    have : Infinite (S.model.Dom S.W₀ .e) := h
    exact verdict_holds S.model_isModel (holdsAx_eq.2 (SymBase.holds_axInf .e)) |>.2

end axiom_of_infinity_e

namespace axiom_of_infinity_t

/-- Separable collapses give infinitely many propositions
(`SymBase.infinite_props_of_separable`). -/
theorem axiom_of_infinity_t : Statements.Arguments.symmetric_ideally_full.axiom_of_infinity_t.axiom_of_infinity_t :=
  fun S h => by
    have := SymBase.infinite_props_of_separable h
    exact verdict_holds S.model_isModel (holdsAx_eq.2 (SymBase.holds_axInf (.rel .t))) |>.2

end axiom_of_infinity_t
namespace barcan_surjective

/-- BF at every type (`SymBase.bf_of_surjective`): a surjective arrow is surjective on every
domain, by pulling back. -/
theorem barcan_r : Statements.Arguments.symmetric_ideally_full.barcan_surjective.barcan_r :=
  fun S h hfp => verdict_holds S.model_isModel
    (holdsAx_indexed.2 fun σ _ => SymBase.bf_of_surjective h hfp σ) |>.2

end barcan_surjective

namespace boolean_completeness

/-- Dorr's main theorem: a property's least upper bound is the union of its instances' hulls
(`SymBase.lub_of_hull`), for a base with any number of objects. -/
theorem boolean_completeness_r : Statements.Arguments.symmetric_ideally_full.boolean_completeness.boolean_completeness_r :=
  fun S hH => verdict_holds S.model_isModel (S.model.entails_holds S.model_isModel
    P.BooleanCompleteness.of_lub.entails
    (holdsAx_indexed.2 fun ρ _ => SymBase.holds_bc_lub hH ρ)) |>.2

end boolean_completeness

end symmetric_ideally_full

/-! ## Arguments of the finite-support models on one object -/

namespace finite_support_one_object

namespace actual_world

/-- The actual-world proposition is in the domain (`actuality_of_pinned_one`). -/
theorem actuality : Statements.Arguments.finite_support_one_object.actual_world.actuality :=
  fun M _ _ _ h => verdict_holds (model_isModel M) (holdsAx_eq.2 (actuality_of_pinned_one M h)) |>.2

end actual_world

namespace collapsing_atomless

theorem atomicity_t : Statements.Arguments.finite_support_one_object.collapsing_atomless.atomicity_t :=
  fun M _ _ _ h => verdict_fails (model_isModel M)
    (not_holdsAx_of (Ax := P.AtomicityT.schema) rfl (not_atomicityT_of_collapseUnpinned M h)) |>.2

theorem atomicity_r : Statements.Arguments.finite_support_one_object.collapsing_atomless.atomicity_r :=
  fun M _ _ _ h => verdict_fails (model_isModel M)
    (not_holdsAx_of (Ax := P.Atomicity.schema) (a := P.Atomicity.quoted .t) ⟨.t, by simp, rfl⟩
      (not_atomicityT_of_collapseUnpinned M h)) |>.2

end collapsing_atomless

namespace barcan_positive

/-- The property of being positive: an arrow sending `0` to a positive number sends
everything there, being monotone, but some arrow does so while `0` is not positive
(`MonoidModel.not_bf_e`). -/
theorem barcan_r : Statements.Arguments.finite_support_one_object.barcan_positive.barcan_r :=
  fun M _ _ _ ⟨hmono, g, hg⟩ => verdict_fails (model_isModel M) (not_holdsAx_of ⟨.e, trivial, rfl⟩
    (not_bf_e M (· ≠ 0) (· ≠ 0) 0
      (fun k y hk => by have := hmono k (Nat.zero_le y); simp only at this; omega)
      ⟨g, hg.ne', 0, by simp⟩)) |>.2

end barcan_positive

end finite_support_one_object

end Classicism.Map.Arguments
